name: 自動更新股票分析資料

on:
  schedule:
    - cron: '0 21 * * *'  # 每天 UTC 21:00 = 台灣早上 5:00
  workflow_dispatch:

jobs:
  update-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: 下載他自己的 repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 安裝 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 安裝相關套件
        run: |
          pip install yfinance pandas

      - name: 執行股票分析更新
        run: |
          python scripts/update_stocks.py

      - name: 提交更新的 JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/data/stocks.json
          git commit -m "自動更新 stocks.json" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
